package(default_visibility = ["//visibility:public"])

sh_binary(
    name = "dhall-library",
    srcs = ["dhall-library.sh"],
)

sh_binary(
    name = "dhall-output",
    srcs = ["dhall-output.sh"],
)

sh_binary(
    name = "dhall-hash",
    srcs = ["dhall-hash.sh"],
)
